- name: This will set up a vsftpd vulnerability on the Ubuntu 18.04 machine
  hosts: Ubuntu-18
  remote_user: vagrant
  gather_facts: no
  tasks:
    - name: Get git directory
      shell: git clone https://github.com/nikdubois/vsftpd-2.3.4-infected.git
      
    - name: Run shell script on remote server
      script: setup.sh
      args:
        chdir: /home/vagrant/vsftpd-2.3.4-infected/

    - name: Run vsftpd
      shell: sudo /usr/local/sbin/vsftpd &
